teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.25
      y: 0.25

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.4

    enable_button: 5
