<?xml version="1.0" ?>
<robot name="simrobo" xmlns:xacro="http://www.ros.org/wiki/xacro">  
  <!-- include xacro files -->
  <xacro:include filename="$(find simrobo_description)/urdf/body/body.urdf.xacro" />
  <xacro:include filename="$(find simrobo_description)/urdf/wheel/wheel.urdf.xacro" />
  <xacro:include filename="$(find simrobo_description)/urdf/wheel/caster.urdf.xacro" />
  <xacro:include filename="$(find simrobo_description)/urdf/sensors/lidar.urdf.xacro" />
  <xacro:include filename="$(find simrobo_description)/urdf/sensors/velodyne.urdf.xacro" />
  <!--xacro:include filename="$(find simrobo_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find simrobo_description)/urdf/sensors/gps.urdf.xacro" />
  <xacro:include filename="$(find simrobo_description)/urdf/sensors/camera.urdf.xacro" / -->
  <xacro:include filename="$(find simrobo_description)/urdf/simrobo.ros2_control.xacro" />
  
  <!-- arg -->
  <xacro:arg name="use_ignition" default="true"/>
  <xacro:arg name="use_3d_lidar" default="false"/>
  <xacro:arg name="gpu" default="false"/>
  
  <!-- property -->
  <xacro:property name="use_ignition" value="$(arg use_ignition)"/>
  <xacro:property name="use_3d_lidar" value="$(arg use_3d_lidar)"/>
  <xacro:property name="gpu" value="$(arg gpu)"/>
  <xacro:property name="body_depth" value="0.4"/>
  <xacro:property name="body_width" value="0.3"/>
  <xacro:property name="body_height" value="0.2"/>
  <xacro:property name="body_mass" value="1"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_clearance" value="0.03"/>
  <xacro:property name="wheel_mass" value="0.4"/>
  <xacro:property name="wheel_joint_x" value="-0.1"/>
  <xacro:property name="caster_radius" value="0.08"/>
  <xacro:property name="caster_mass" value="0.2"/>
  <xacro:property name="caster_joint_x" value="0.1"/>
  <xacro:property name="lidar_2d_radius" value="0.04"/>
  <xacro:property name="lidar_2d_length" value="0.04"/>
  <xacro:property name="lidar_2d_mass" value="0.015"/>
  <xacro:property name="lidar_3d_radius" value="0.103"/>
  <xacro:property name="lidar_3d_length" value="0.0727"/>
  <xacro:property name="lidar_3d_mass" value="0.830"/>
  <xacro:property name="lidar_3d_mount_mass" value="0.4"/>
  <xacro:property name="imu_length" value="0.02"/>
  <xacro:property name="imu_height" value="0.01"/>
  <xacro:property name="imu_mass" value="0.01"/>
  <xacro:property name="gps_length" value="0.02"/>
  <xacro:property name="gps_height" value="0.01"/>
  <xacro:property name="gps_mass" value="0.01"/>
  <xacro:property name="camera_depth" value="0.02"/>
  <xacro:property name="camera_width" value="0.12"/>
  <xacro:property name="camera_height" value="0.02"/>
  <xacro:property name="camera_mass" value="0.1"/>
  <xacro:property name="camera_pos_z" value="0.15"/>
  
  <!-- ======== Body Description ======== -->
  <link name="base_footprint"/>
  <xacro:body name="base_link" depth="${body_depth}" width="${body_width}" height="${body_height}" mass="${body_mass}">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </xacro:body>
  
  <!-- ======== Wheel Description ======== -->
  <xacro:wheel name="left" parent="base_link" radius="${wheel_radius}" clearance="${wheel_clearance}" mass="${wheel_mass}">
    <origin xyz="${wheel_joint_x} ${body_width/2+wheel_clearance/2} 0" rpy="${-pi/2} 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="right" parent="base_link" radius="${wheel_radius}" clearance="${wheel_clearance}" mass="${wheel_mass}">
    <origin xyz="${wheel_joint_x} ${-body_width/2-wheel_clearance/2} 0" rpy="${-pi/2} 0 0"/>
  </xacro:wheel>
  <xacro:caster name="front" parent="base_link" radius="${caster_radius}" mass="${caster_mass}">
    <origin xyz="${caster_joint_x} 0 ${-wheel_radius+caster_radius}" rpy="0 0 0"/>
  </xacro:caster>
  
  <!-- ======== Sensors Description ======== -->
  <xacro:if value="${use_3d_lidar}">
    <link name="lidar_mount">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${lidar_3d_mount_mass}"/>
        <inertia ixx="${lidar_3d_mount_mass/12*(3*0.08*0.08+0.3*0.3)}" ixy="0" ixz="0"
                 iyx="0" iyy="${lidar_3d_mount_mass/12*(3*0.08*0.08+0.3*0.3)}" iyz="0.0"
                 izx="0" izy="0" izz="${lidar_3d_mount_mass/2*0.08*0.08}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.08" length="0.3"/>
        </geometry>
        <material name="lidar_mount_color">
          <color rgba="1.0 1.0 0.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder  radius="0.08" length="0.3"/>
        </geometry>
      </collision>
    </link>
    <joint name="lidar_mount_joint" type="fixed">
      <origin xyz="0 0 ${body_height+0.3/2}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="lidar_mount"/>
    </joint>
    <xacro:velodyne name="velodyne" gpu="${gpu}" parent="lidar_mount" radius="${lidar_3d_radius}" length="${lidar_3d_length}" mass="${lidar_3d_mass}">
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
    </xacro:velodyne>
  </xacro:if>
  <xacro:unless value="${use_3d_lidar}">
    <xacro:lidar name="laser" use_ignition="${use_ignition}" gpu="${gpu}" parent="base_link" radius="${lidar_2d_radius}" length="${lidar_2d_length}" mass="${lidar_2d_mass}">
      <origin xyz="0 0 ${body_height+lidar_2d_length/2}" rpy="0 0 0"/>
    </xacro:lidar>
  </xacro:unless>
  <!--xacro:imu name="imu" parent="base_link" length="${imu_length}" height="${imu_height}" mass="${imu_mass}">
    <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
  </xacro:imu>
  <xacro:gps name="gps" parent="base_link" length="${gps_length}" height="${gps_height}" mass="${gps_mass}">
    <origin xyz="0 0 ${body_height/3}" rpy="0 0 0"/>
  </xacro:gps>
  <xacro:camera name="camera" parent="base_link" depth="${camera_depth}" width="${camera_width}" height="${camera_height}" mass="${camera_mass}">
    <origin xyz="${(body_depth+camera_depth)/2} 0 ${camera_pos_z}" rpy="0 0 0"/>
  </xacro:camera -->
  
  <!-- ======== ros2_control ======== -->
  <xacro:simrobo_ros2_control name="simrobo" use_ignition="${use_ignition}"/>
  
</robot>
