<?xml version="1.0" ?>
<robot name="simrobo" xmlns:xacro="http://www.ros.org/wiki/xacro">  
  <!-- include xacro files -->
  <xacro:include filename="$(find simrobo_description)/urdf/body/body.urdf.xacro" />
  <xacro:include filename="$(find simrobo_description)/urdf/wheel/wheel.urdf.xacro" />
  <xacro:include filename="$(find simrobo_description)/urdf/wheel/caster.urdf.xacro" />
  
  <!-- property -->
  <xacro:property name="body_depth" value="0.14"/>
  <xacro:property name="body_width" value="0.1"/>
  <xacro:property name="body_height" value="0.2"/>
  <xacro:property name="body_mass" value="1"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_clearance" value="0.01"/>
  <xacro:property name="wheel_mass" value="0.4"/>
  <xacro:property name="wheel_joint_x" value="0.1"/>
  <xacro:property name="caster_radius" value="0.04"/>
  <xacro:property name="caster_mass" value="0.2"/>
  <xacro:property name="caster_joint_x" value="-0.1"/>
  
  <!-- ======== Body Description ======== -->
  <link name="base_footprint"/>
  <xacro:body name="base_link" depth="${body_depth}" width="${body_width}" height="${body_height}" mass="${body_mass}">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </xacro:body>
  
  <!-- ======== Wheel Description ======== -->
  <xacro:wheel name="left" parent="base_link" radius="${wheel_radius}" clearance="${wheel_clearance}" mass="${wheel_mass}">
    <origin xyz="${wheel_joint_x} ${body_width/2+wheel_clearance/2} 0" rpy="${-pi/2} 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="right" parent="base_link" radius="${wheel_radius}" clearance="${wheel_clearance}" mass="${wheel_mass}">
    <origin xyz="${wheel_joint_x} ${-body_width/2-wheel_clearance/2} 0" rpy="${-pi/2} 0 0"/>
  </xacro:wheel>
  <xacro:caster name="back" parent="base_link" radius="${caster_radius}" mass="${caster_mass}">
    <origin xyz="${caster_joint_x} 0 ${-wheel_radius+caster_radius}" rpy="0 0 0"/>
  </xacro:caster>
</robot>
