teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical & horizontal
      x: 1
      y: 0
    scale_linear:
      x: 0.75
      y: 0.75

    axis_angular:  # Right thumb stick rotate
      yaw: 0
    scale_angular:
      yaw: 0.8

    enable_button: 5  # RB button
