<?xml version="1.0" ?>
<robot name="body" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:macro name="body" params="name *origin">
    <xacro:property name="BODY_DEPTH" value="0.14"/>
    <xacro:property name="BODY_WIDTH" value="0.1"/>
    <xacro:property name="BODY_HEIGHT" value="0.2"/>
    <xacro:property name="MASS" value="1"/>
    
    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${MASS}" />
        <inertia ixx="${MASS/12*(BODY_WIDTH*BODY_WIDTH+BODY_HEIGHT*BODY_HEIGHT)}" ixy="0" ixz="0"
                 iyx="0" iyy="${MASS/12*(BODY_DEPTH*BODY_DEPTH+BODY_HEIGHT*BODY_HEIGHT)}" iyz="0"
                 izx="0" izy="0" izz="${MASS/12*(BODY_DEPTH*BODY_DEPTH+BODY_WIDTH*BODY_WIDTH)}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${BODY_HEIGHT/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${BODY_DEPTH} ${BODY_WIDTH} ${BODY_HEIGHT}"/>
        </geometry>
        <material name="body_color">
          <color rgba="1.0 0.0 0.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${BODY_HEIGHT/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${BODY_DEPTH} ${BODY_WIDTH} ${BODY_HEIGHT}"/>
        </geometry>
      </collision>
    </link>
    
    <gazebo reference="${name}">
      <mu1 value="0.8"/>
      <mu2 value="0.8"/>
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <fdir1 value="0 1 0"/>
    </gazebo>
    
    <joint name="body_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="base_footprint"/>
      <child link="${name}"/>
      <axis xyz="0.0 0.0 1.0"/>
    </joint>
  </xacro:macro>
</robot>
