<?xml version="1.0" ?>
<robot name="body" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:macro name="body" params="name depth width height mass *origin">
    
    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}" />
        <inertia ixx="${mass/12*(width*width+height*height)}" ixy="0" ixz="0"
                 iyx="0" iyy="${mass/12*(depth*depth+height*height)}" iyz="0"
                 izx="0" izy="0" izz="${mass/12*(depth*depth+width*width)}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${depth} ${width} ${height}"/>
        </geometry>
        <material name="body_color">
          <color rgba="1.0 1.0 0.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${depth} ${width} ${height}"/>
        </geometry>
      </collision>
    </link>
    
    <gazebo reference="${name}">
      <material>Gazebo/Yellow</material>
      <mu1 value="0.8"/>
      <mu2 value="0.8"/>
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <fdir1 value="0 1 0"/>
    </gazebo>
    
    <joint name="body_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="base_footprint"/>
      <child link="${name}"/>
      <axis xyz="0.0 0.0 1.0"/>
    </joint>
  </xacro:macro>
</robot>
